[package]
name = "iota-streams-core"
version = "0.1.2"
authors = ["Vlad Semenov <vlad.semenov@iota.org>", "Dyrell Chapman <dyrell.chapman@iota.org>", "Brord van Wierst <brord@iota.org>", "Arnau Orriols <arnau.orriols@iota.org>"]
edition = "2018"
license = "Apache-2.0/MIT"
readme = "README.md"
keywords = ["iota", "streams", "core"]
description = "A rust implementation of the IOTA Streams core utils"

[features]
default = ["std"]
# enable std
std = ["rand/std", "digest/std", "hex/std"]
err-location-log = []
sync-spin = ["spin"]
sync-parking-lot = ["parking_lot"]

[dependencies]
# digest version should correspond to curve25519-dalek's version
digest = { version = "0.9", default-features = false }
rand = { version = "0.7", default-features = false}
hashbrown = { version = "0.11.2", default-features = false, optional = false, features = ["ahash"] }
hex = { version = "0.4", default-features = false, optional = false, features = ["alloc"] }
anyhow = { version = "1.0", default-features = false, features = ["std"], optional = false }
async-trait = { version = "0.1", optional = false }
parking_lot = { version = "0.11.2", optional = true }
spin = { version = "0.9.2", default-features = false, features = ["mutex", "spin_mutex"], optional = true }
rustversion = "1.0"
iota-crypto = { version = "0.9.1", features = ["blake2b"] }

# thiserror = { version = "1.0.22", default-features = false, optional = false }
displaydoc = { version = "0.2", default-features = false, optional = false }

[target.'cfg(target_arch = "wasm32")'.dependencies]
web-sys = { version = "0.3", features = ["console"] }

[dev-dependencies]
criterion = "0.3"

